include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-dynamic: true
  errors:
    # allow having TODOs in the code
    todo: ignore
  exclude:

linter:
  rules:
    # STYLE
    camel_case_types: true
    camel_case_extensions: true
    library_names: true
    file_names: true
    library_prefixes: true
    curly_braces_in_flow_control_structures: true
    avoid_field_initializers_in_const_classes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    directives_ordering: true
#    lines_longer_than_80_chars

    # DOCUMENTATION
    slash_for_doc_comments: true
    package_api_docs: true # prefer

    # USAGE
    implementation_imports: true
    avoid_relative_lib_imports: true # prefer
    prefer_relative_imports: true # prefer
    prefer_adjacent_string_concatenation: true
    unnecessary_brace_in_string_interps: true # avoid
    prefer_iterable_whereType: true
    unnecessary_lambdas: true
    prefer_equal_for_default_values: true
    avoid_init_to_null: true
    unnecessary_getters_setters: true
    unnecessary_this: true
    prefer_initializing_formals: true
    type_init_formals: true
    empty_constructor_bodies: true
    unnecessary_new: true
    unnecessary_const: true
    avoid_catching_errors: true
    use_rethrow_when_possible: true
    avoid_print: true
    avoid_unnecessary_containers: true

    # DESIGN
    use_to_and_as_if_applicable: true # prefer
    prefer_final_fields: true # prefer
    avoid_setters_without_getters: true
    avoid_private_typedef_functions: true # prefer
    hash_and_equals: true
    avoid_null_checks_in_equality_operators: true

    # ignore
    no_leading_underscores_for_local_identifiers: false
    depend_on_referenced_packages: false
    library_private_types_in_public_api: false
    use_build_context_synchronously: false