name: flutter_simple_map
description: Create beautiful maps in flutter with GeoJson using a declarative api, highly customizable, pure Flutter.
version: 0.1.0
repository: https://github.com/leanhtuan1994/flutter_geo_map

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  
flutter:
